# -*- coding: utf-8 -*-
"""thaicons.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uJ69L-ptdc7UsqaIpd0yY8HxNNmwehp
"""

import tkinter as tk
import random

# Thai consonants and their names
consonants = [
    ("ก", "gor kai"),
    ("ข", "khor khai"),
    ("ฃ", "khor khuat"),
    ("ค", "khor khon"),
    ("ฅ", "khor ra-kang"),
    ("ฆ", "khor khok"),
    ("ง", "ngor ngu"),
    ("จ", "jor jaan"),
    ("ฉ", "chor ching"),
    ("ช", "chor chang"),
    ("ซ", "sor so"),
    ("ฌ", "cho ching"),
    ("ญ", "yor ying"),
    ("ฎ", "dor cha-da"),
    ("ฏ", "tor pa-tak"),
    ("ฐ", "thaw than"),
    ("ฑ", "thaw thung"),
    ("ฒ", "thaw thahan"),
    ("ณ", "nor nu"),
    ("ด", "dor dek"),
    ("ต", "tor tao"),
    ("ถ", "thaw thang"),
    ("ท", "thaw thang"),
    ("ธ", "thor thang"),
    ("น", "nor na"),
    ("บ", "bor bai mai"),
    ("ป", "por pla"),
    ("ผ", "phor phueng"),
    ("ฝ", "for fang"),
    ("พ", "phor phung"),
    ("ฟ", "for fan"),
    ("ภ", "phor sa-la"),
    ("ม", "mor ma"),
    ("ย", "yor yak"),
    ("ร", "ror ruea"),
    ("ล", "lor ling"),
    ("ว", "wor waen"),
    ("ศ", "sor sa-la"),
    ("ษ", "sor ruea"),
    ("ส", "sor so"),
    ("ห", "hor heep"),
    ("ฬ", "lor cha-la"),
    ("อ", "or ang"),
    ("ฮ", "hor nok-huk"),
]

class FlashcardGame:
    def __init__(self, root):
        self.root = root
        self.root.title("Thai Consonant Flashcard Game")
        self.root.geometry("400x400")

        self.current_consonant = None

        # Label to show consonant or name
        self.label = tk.Label(self.root, text="Welcome to the Thai Consonant Game!", font=("Helvetica", 24), width=20, height=5)
        self.label.pack(pady=50)

        # Button to flip the card
        self.flip_button = tk.Button(self.root, text="Flip Card", font=("Helvetica", 14), command=self.flip_card)
        self.flip_button.pack()

        # Button to show next consonant
        self.next_button = tk.Button(self.root, text="Next", font=("Helvetica", 14), command=self.next_card)
        self.next_button.pack(pady=10)

        self.next_card()  # Display the first consonant

    def flip_card(self):
        # Flip card by showing name if consonant is displayed
        if self.current_consonant:
            consonant, name = self.current_consonant
            current_text = self.label.cget("text")

            # Show name or consonant
            if current_text == consonant:
                self.label.config(text=name)
            else:
                self.label.config(text=consonant)

    def next_card(self):
        # Get random consonant
        self.current_consonant = random.choice(consonants)
        consonant, name = self.current_consonant

        # Display the consonant
        self.label.config(text=consonant)


# Set up the Tkinter window and game
root = tk.Tk()
game = FlashcardGame(root)
root.mainloop()